
package br.com.navita.mobile.push.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PushException", targetNamespace = "http://push.console.mobile.navita.com.br/")
public class PushException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 9022096429087908049L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PushException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PushException_Exception(String message, PushException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PushException_Exception(String message, PushException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.navita.mobile.push.ws.client.PushException
     */
    public PushException getFaultInfo() {
        return faultInfo;
    }

}
