
package br.com.navita.mobile.push.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "push", targetNamespace = "http://push.console.mobile.navita.com.br/", wsdlLocation = "http://192.168.10.104:8888/mobile-console/push-ws?wsdl")
public class Push
    extends Service
{

    private final static URL PUSH_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.navita.mobile.push.ws.client.Push.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.navita.mobile.push.ws.client.Push.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.10.104:8888/mobile-console/push-ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.10.104:8888/mobile-console/push-ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PUSH_WSDL_LOCATION = url;
    }

    public Push(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Push() {
        super(PUSH_WSDL_LOCATION, new QName("http://push.console.mobile.navita.com.br/", "push"));
    }

    /**
     * 
     * @return
     *     returns PushService
     */
    @WebEndpoint(name = "pushPort")
    public PushService getPushPort() {
        return super.getPort(new QName("http://push.console.mobile.navita.com.br/", "pushPort"), PushService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PushService
     */
    @WebEndpoint(name = "pushPort")
    public PushService getPushPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://push.console.mobile.navita.com.br/", "pushPort"), PushService.class, features);
    }

}
