/*
 * Copyright 2014 Navita Tecnologia.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package br.com.navita.mobile.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "singlePointService", targetNamespace = "http://ws.mobile.navita.com.br/", wsdlLocation = "http://127.0.0.1:8889/navita-mobile-sample-app/ws?wsdl")
public class SinglePointService
    extends Service
{

    private final static URL SINGLEPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.navita.mobile.ws.client.SinglePointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.navita.mobile.ws.client.SinglePointService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8889/navita-mobile-sample-app/ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8889/navita-mobile-sample-app/ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SINGLEPOINTSERVICE_WSDL_LOCATION = url;
    }

    public SinglePointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SinglePointService() {
        super(SINGLEPOINTSERVICE_WSDL_LOCATION, new QName("http://ws.mobile.navita.com.br/", "singlePointService"));
    }

    /**
     * 
     * @return
     *     returns SinglePoint
     */
    @WebEndpoint(name = "singlePointPort")
    public SinglePoint getSinglePointPort() {
        return super.getPort(new QName("http://ws.mobile.navita.com.br/", "singlePointPort"), SinglePoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SinglePoint
     */
    @WebEndpoint(name = "singlePointPort")
    public SinglePoint getSinglePointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mobile.navita.com.br/", "singlePointPort"), SinglePoint.class, features);
    }

}
