/*
 * Copyright 2014 Navita Tecnologia.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package br.com.navita.mobile.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "singlePoint", targetNamespace = "http://ws.mobile.navita.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SinglePoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.navita.mobile.ws.client.GenericBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = "http://ws.mobile.navita.com.br/", className = "br.com.navita.mobile.ws.client.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://ws.mobile.navita.com.br/", className = "br.com.navita.mobile.ws.client.ExecuteResponse")
    public GenericBean execute(
        @WebParam(name = "arg0", targetNamespace = "")
        GenericBean arg0);

}
